# Generated by Django 4.0.4 on 2022-04-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contributor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('url2', models.URLField(blank=True, default='', null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'lancers',
                'verbose_name_plural': 'lancers',
                'ordering': ['-created_at'],
            },
        ),
    ]
